# .travis.yml 



# for auto testing



language: python

python:

  - "3.4"

# dependencies installation

install:

  - pip install -r requirements.txt

# add environment variable

before_script:

  - psql -c "create user erick with password 'Tubezzzz35' createdb;" -U postgres
  - psql -c 'CREATE DATABASE flask_api;' -U postgres
  - psql -c CREATE TABLE users (
            user_id SERIAL PRIMARY KEY,
            user_name VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL UNIQUE,
            password VARCHAR(255)
        );


# start test

script:

  - py.test --cov=app

# send info to coveralls

after_success:

   coveralls