# .travis.yml 



# for auto testing



language: python

python:

  - "3.4"

# dependencies installation

install:

  - pip install -r requirements.txt

# add environment variable

before_script:

  - export DB_NAME="flask-api"
  - psql -c 'CREATE DATABASE flask-api;' -U postgres

# start test

script:

  - py.test --cov=app

# send info to coveralls

after_success:

   coveralls